language: dart
dart:
  - "2.0.0"
services:
  - docker
before_install:
  - docker pull mongo:4.0
  - docker run -d -p 27017:27017 mongo:4.0
  - docker ps -a
dart_task:
  - dartanalyzer: --fatal-warnings lib
  - dartfmt
  - test: --platform vm