name: rest_api_server
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/alexd1971/rest_api_server
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.11.3
  jaguar_jwt: ^2.1.5
  mongo_dart: ^0.3.3
  nanoid: ^0.0.4
  path: ^1.6.2
  data_model:
    git:
      url: https://github.com/alexd1971/data_model.git
      ref: master
  shelf: ^0.7.3

dev_dependencies:
  test: ^1.0.0
  stream_channel: ^1.6.8
  mockito: ^3.0.0

